[package]
name = "snake_simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy-inspector-egui = "0.32.0"
bevy_egui = "0.35.1"
pathfinding = "4.14.0"
rand = "0.9.2"
rurel = "0.6.0"
smart-default = "0.7.1"
uuid = { version = "1.18.1", features = ["v4"] }
